<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends EntityRepository
{
    public function getExpiredTokens(\DateTime $date)
    {
        return $this->createQueryBuilder('t')
            ->where('t.expirationDate <= :date')
            ->setParameter(':date', $date)
            ->getQuery()
            ->getResult()
        ;
    }

    public function getTokenWithUser($tokenCode)
    {
        return $this->createQueryBuilder('t')
            ->where('t.code = :tokenCode')
            ->setParameter(':tokenCode', $tokenCode)
            ->innerJoin('t.user', 'u')
            ->addSelect('u')
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
