<?php

/**
 * Token Repository
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends EntityRepository
{
    /**
     * Get the expired tokens
     * @access public
     * @param \DateTime $date
     * 
     * @return array
     */
    public function getExpiredTokens(\DateTime $date)
    {
        return $this->createQueryBuilder('t')
            ->where('t.expirationDate <= :date')
            ->setParameter(':date', $date)
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * Get a Token with his User
     * @access public
     * @param string $tokenCode
     * 
     * @return mixed Token | null
     */
    public function getTokenWithUser($tokenCode)
    {
        return $this->createQueryBuilder('t')
            ->where('t.code = :tokenCode')
            ->setParameter(':tokenCode', $tokenCode)
            ->innerJoin('t.user', 'u')
            ->addSelect('u')
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
