<?php

namespace AppBundle\Repository;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get a Trick with slug
     * @access public
     * @param string $slug
     * 
     * @return mixed Trick | null
     */
    public function getTrick($slug)
    {
        return $this->createQueryBuilder('t')
            ->where('t.slug = :slug')
            ->setParameter('slug', $slug)
            ->innerJoin('t.user', 'u')
            ->addSelect('u')
            ->innerJoin('t.category', 'cat')
            ->addSelect('cat')
            ->leftJoin('t.images', 'img')
            ->addSelect('img')
            ->leftJoin('t.videos', 'vid')
            ->addSelect('vid')
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
