<?php

namespace AppBundle\Repository;

/**
 * TrickImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickImageRepository extends \Doctrine\ORM\EntityRepository
{
}
